#!/usr/bin/env python3
"""SAM Trader V3 — First-run wizard. Generates .env from interactive prompts."""

from __future__ import annotations

import getpass
import hashlib
import os
import sys
from pathlib import Path


def _md5(val: str) -> str:
    return hashlib.md5(val.encode()).hexdigest()


def main() -> int:
    env_path = Path(".env")
    if env_path.exists():
        ans = input(".env already exists. Overwrite? [y/N]: ").strip().lower()
        if ans not in ("y", "yes"):
            print("Aborted.")
            return 1

    print("=" * 60)
    print("SAM Trader V3 — First Run Wizard")
    print("=" * 60)

    trader_id = input("Trader ID [sam_trader]: ").strip() or "sam_trader"
    env = input("Environment (paper/live) [paper]: ").strip() or "paper"

    # Futu
    futu_enabled = input("Enable Futu broker? [y/N]: ").strip().lower() in ("y", "yes")
    futu_pwd_md5 = ""
    futu_unlock_md5 = ""
    if futu_enabled:
        raw = getpass.getpass("Futu account password (will be hashed): ")
        if raw:
            futu_pwd_md5 = _md5(raw)
        raw_unlock = getpass.getpass(
            "Futu trade-unlock password (optional, will be hashed): "
        )
        if raw_unlock:
            futu_unlock_md5 = _md5(raw_unlock)

    # IB
    ib_enabled = input("Enable IBKR broker? [y/N]: ").strip().lower() in ("y", "yes")
    tws_user = ""
    tws_pass = ""
    if ib_enabled:
        tws_user = input("TWS User ID: ").strip()
        tws_pass = getpass.getpass("TWS Password: ")

    # Secrets
    pg_pass = getpass.getpass("PostgreSQL password [sam_secret]: ") or "sam_secret"
    redis_pass = getpass.getpass("Redis password (leave empty for none): ")

    lines = [
        "# SAM Trader V3 — Environment variables",
        "# Generated by scripts/wizard.py",
        "",
        f"TRADER_ID={trader_id}",
        f"SAM_ENV={env}",
        "",
        "# ---- Futu OpenD ----",
        f"FUTU_ENABLED={'true' if futu_enabled else 'false'}",
        "FUTU_OPEND_HOST=sam-futu-opend",
        "FUTU_OPEND_PORT=11111",
        f"FUTU_ACCOUNT_PWD_MD5={futu_pwd_md5}",
        f"FUTU_UNLOCK_PWD_MD5={futu_unlock_md5}",
        "FUTU_TRD_ENV=SIMULATE",
        "FUTU_TRD_MARKET=US",
        "",
        "# ---- IB Gateway ----",
        f"IB_ENABLED={'true' if ib_enabled else 'false'}",
        "IB_GATEWAY_HOST=sam-ib-gateway",
        "IB_GATEWAY_PORT=4004",
        "IB_TRADING_MODE=paper",
        f"TWS_USERID={tws_user}",
        f"TWS_PASSWORD={tws_pass}",
        "",
        "# ---- Redis ----",
        "REDIS_HOST=sam-redis",
        "REDIS_PORT=6379",
        f"REDIS_PASSWORD={redis_pass}",
        "",
        "# ---- PostgreSQL ----",
        "POSTGRES_HOST=sam-postgres",
        "POSTGRES_PORT=5432",
        "POSTGRES_DB=sam_trader",
        "POSTGRES_USER=sam",
        f"POSTGRES_PASSWORD={pg_pass}",
        "",
        "# ---- State persistence ----",
        "STATE_SAVE_ENABLED=true",
        "STATE_LOAD_ENABLED=true",
        "",
        "# ---- Backup ----",
        "BACKUP_HOST_DIR=~/Documents/ai_agent_docs/backup-sam_trader_v3",
        "BACKUP_RETENTION_DAYS=30",
        "",
        "# ---- Logging ----",
        "LOG_LEVEL=INFO",
        "",
        "# ---- Deployment window (HKT) ----",
        "DEPLOY_WINDOW=05:00-08:00",
        "",
        "# ---- Pre-market pipeline ----",
        "PIPELINE_SCHEDULE=08:00",
        "PIPELINE_MARKET=US",
    ]

    env_path.write_text("\n".join(lines) + "\n")
    os.chmod(env_path, 0o600)
    print(f"\nINFO: .env written to {env_path.resolve()}")
    print("INFO: File permissions set to 600 (owner read/write only)")
    print("\nNext steps:")
    print("  1. Review .env and edit any advanced settings")
    print("  2. Run: ./deploy.sh --with-futu start")
    print(
        "  3. Daily updates: ./deploy.sh --build"
        " && docker exec sam-services sam apply"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
